AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: "Template to setup the RDS app with AWS and Sumo Logic resources for AWS Observability Solution."

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: "Sumo Logic Access Configuration (Required)"
        Parameters:
          - Section1aSumoDeployment
          - Section1bSumoAccessID
          - Section1cSumoAccessKey
          - Section1dSumoOrganizationId
          - Section1eRemoveSumoResourcesOnDeleteStack

      - Label:
          default: "Sumo Logic AWS Resources Tagging Configuration (Required)"
        Parameters:
          - Section2aTagExistingAWSResources
          - Section2bAccountAlias
          - Section2cFilterExpression

      - Label:
          default: "App Details - Sumo Logic App Configuration"
        Parameters:
          - Section3aInstallApp
          - Section3bCollectorName

      - Label:
          default: "App Details - CloudWatch Metrics Source Configuration"
        Parameters:
          - Section4aCreateCloudWatchMetricsSource
          - Section4bCloudWatchMetricsSourceName
          - Section4cCloudWatchExistingSourceAPIUrl

      - Label:
          default: "App Details - CloudTrail Log Source Configuration"
        Parameters:
          - Section5aCreateCloudTrailBucket
          - Section5bCloudTrailLogsBucketName
          - Section5cCreateCloudTrailLogSource
          - Section5dCloudTrailBucketPathExpression
          - Section5eCloudTrailLogsSourceName
          - Section5fCloudTrailLogsAPIUrl

      - Label:
          default: "Local Parameters. Do Not Edit the values."
        Parameters:
          - Section6aParentStackLambdaARN
          - Section6bTemplatesBucketName

    ParameterLabels:
      Section1aSumoDeployment:
        default: "Sumo Logic Deployment Name"
      Section1bSumoAccessID:
        default: "Sumo Logic Access ID"
      Section1cSumoAccessKey:
        default: "Sumo Logic Access Key"
      Section1dSumoOrganizationId:
        default: "Sumo Logic Organization Id"
      Section1eRemoveSumoResourcesOnDeleteStack:
        default: "Delete Sumo Logic Resources when stack is deleted"

      Section2aTagExistingAWSResources:
        default: "Tag Existing AWS RDS Resources."
      Section2bAccountAlias:
        default: "Alias for AWS Account Identification"
      Section2cFilterExpression:
        default: "Filter Regular expression"

      Section3aInstallApp:
        default: "Install Sumo Logic App"
      Section3bCollectorName:
        default: "Sumo Logic Collector Name"

      Section4aCreateCloudWatchMetricsSource:
        default: "Create Sumo Logic CloudWatch Metrics Source"
      Section4bCloudWatchMetricsSourceName:
        default: "Sumo Logic CloudWatch Metrics Source Name"
      Section4cCloudWatchExistingSourceAPIUrl:
        default: "Existing Sumo Logic CloudWatch Metrics Source API URL"

      Section5aCreateCloudTrailBucket:
        default: "Create AWS S3 Bucket"
      Section5bCloudTrailLogsBucketName:
        default: "AWS S3 Bucket Name"
      Section5cCreateCloudTrailLogSource:
        default: "Create Sumo Logic CloudTrail Logs Source"
      Section5dCloudTrailBucketPathExpression:
        default: "Path Expression for the logs"
      Section5eCloudTrailLogsSourceName:
        default: "Sumo Logic CloudTrail Logs Source Name"
      Section5fCloudTrailLogsAPIUrl:
        default: "Existing Sumo Logic CloudTrail Logs Source API URL"

      Section6aParentStackLambdaARN:
        default: "If Any, Lambda ARN from parent Stack"
      Section6bTemplatesBucketName:
        default: "Bucket name for all nested stacks."

Parameters:
  Section1aSumoDeployment:
    Type: String
    AllowedValues:
      - au
      - ca
      - de
      - eu
      - jp
      - us2
      - us1
      - in
      - fed
    Description: "Enter au, ca, de, eu, jp, us2, in, fed or us1."
  Section1bSumoAccessID:
    Type: String
    Description: "Sumo Logic Access ID. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access ID can not be empty."
  Section1cSumoAccessKey:
    Type: String
    Description: "Sumo Logic Access Key. Used for Sumo Logic API calls."
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Access Key can not be empty."
    NoEcho: true
  Section1dSumoOrganizationId:
    Description: "Appears on the Account Overview page that displays information about your Sumo Logic organization. Used for IAM Role in Sumo Logic AWS Sources."
    Type: String
    AllowedPattern: ".+"
    ConstraintDescription: "Sumo Logic Organization Id can not be empty."
  Section1eRemoveSumoResourcesOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "To delete collectors, sources and apps when the stack is deleted, set this parameter to True. Default is True.
                  Deletes the resources created by the stack. Deletion of updated resources will be skipped."
    Type: String

  Section2aTagExistingAWSResources:
    Type: String
    Description: "Yes - Tags the existing AWS RDS resources with key - Value as account - account alias.
                  No - Skip AWS Resources tagging."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section2bAccountAlias:
    Type: String
    Description: "Provide an Alias for AWS account for identification in Sumo Logic Explorer View, metrics and logs. Please do not include special characters."
    AllowedPattern: "[a-z0-9]+"
    ConstraintDescription: "Alias must only contain lowercase letters, number and length less than or equal to 30 characters."
    MaxLength: 30
  Section2cFilterExpression:
    Type: String
    Default: ""
    Description: "Provide regular expression for matching aws resources. For eg;- 'InstanceType': 't1.micro.*?'|'name': 'Test.*?']|'stageName': 'prod.*?'|'FunctionName': 'Test.*?'|TableName.*?|'LoadBalancerName': 'Test.*?'|'DBClusterIdentifier': 'Test.*?'|'DBInstanceIdentifier': 'Test.*?'"

  Section3aInstallApp:
    Type: String
    Description: "Yes - Installs the RDS App for the Sumo Logic AWS Observability Solution.
                  No - Skips the installation of this app."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section3bCollectorName:
    Type: String
    Description: "Provide a Sumo Logic Collector Name"
    Default: ""

  Section4aCreateCloudWatchMetricsSource:
    Type: String
    Description: "Yes - Creates a Sumo Logic CloudWatch Metrics Source which collects Metrics for multiple Namespaces from the region selected.
                  No - If you already have a CloudWatch Metrics Source collecting RDS metrics."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section4bCloudWatchMetricsSourceName:
    Type: String
    Description: "Provide a Cloud Watch Metrics Source Name"
    Default: ""
  Section4cCloudWatchExistingSourceAPIUrl:
    Type: String
    Description: "Required when already collecting RDS Metrics. Provide the existing Sumo Logic RDS Metrics Source API URL. Account Field will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section5aCreateCloudTrailBucket:
    Type: String
    Description: "Yes - Create a new CloudTrail bucket in AWS S3.
                  No - Use an existing CloudTrail bucket from AWS S3 which has CloudTrail Logs."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section5bCloudTrailLogsBucketName:
    Type: String
    Description: "Existing Bucket Name - Provide value if the Flag is set to No.
                  New Bucket Name - Provide a unique Bucket Name if the flag is set to Yes."
    Default: ""
  Section5cCreateCloudTrailLogSource:
    Type: String
    Description: "Choose Yes to create Sumo Logic Cloud Trail Log Source with provided bucket Name."
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'
  Section5dCloudTrailBucketPathExpression:
    Type: String
    Description: Path expression to match one or more S3 objects. For example, ABC*.log or ABC.log
    Default: "*"
  Section5eCloudTrailLogsSourceName:
    Type: String
    Description: Change the CloudTrail Source name to be created else default name will be used.
    Default: ""
  Section5fCloudTrailLogsAPIUrl:
    Type: String
    Description: "Required when already collecting CloudTrail logs. Provide the existing Sumo Logic CloudTrail Source API URL. Account Field will be added to the Source. For Source API URL, visit https://help.sumologic.com/03Send-Data/Sources/03Use-JSON-to-Configure-Sources/Local-Configuration-File-Management/View-or-Download-Source-JSON-Configuration"
    Default: ""

  Section6aParentStackLambdaARN:
    Type: String
    Default: "ParentStackLambdaARN"
    Description: Parent Stack Lambda ARN. Do Not Edit the value.
  Section6bTemplatesBucketName:
    Type: String
    Default: "appdevzipfiles-us-east-1"
    Description: Bucket Name for all the nested templates.

Conditions:
  do_not_use_parent_stack: !Equals [ !Ref Section6aParentStackLambdaARN, "ParentStackLambdaARN"]

  tag_existing_aws_resources: !Equals [!Ref Section2aTagExistingAWSResources, 'Yes']
  install_app: !Equals [!Ref Section3aInstallApp, 'Yes']

  update_cloudtrail_logs_source: !And
    - !Not [!Equals [!Ref Section5fCloudTrailLogsAPIUrl, '']]
    - !Not [!Equals [!Ref Section5cCreateCloudTrailLogSource, 'Yes']]

  update_metrics_source: !And
    - !Not [!Equals [!Ref Section4cCloudWatchExistingSourceAPIUrl, '']]
    - !Not [!Equals [!Ref Section4aCreateCloudWatchMetricsSource, 'Yes']]

  create_fer: !Or
    - !Condition update_cloudtrail_logs_source
    - !Not [!Equals [!Ref Section5eCloudTrailLogsSourceName, '']]

Resources:

  CreateCommonResources:
    Type: AWS::CloudFormation::Stack
    Condition: do_not_use_parent_stack
    Properties:
      TemplateURL: !Sub "https://${Section6bTemplatesBucketName}.s3.amazonaws.com/sumologic-aws-observability/apps/common/resources.template.yaml"
      Parameters:
        SumoLogicDeployment: !Ref Section1aSumoDeployment
        SumoLogicAccessID: !Ref Section1bSumoAccessID
        SumoLogicAccessKey: !Ref Section1cSumoAccessKey
        SumoLogicOrganizationId: !Ref Section1dSumoOrganizationId
        RemoveSumoLogicResourcesOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
        AccountAlias: !Ref Section2bAccountAlias
        CollectorName: !Ref Section3bCollectorName
        CreateCloudWatchMetricsSource: !Ref Section4aCreateCloudWatchMetricsSource
        CloudWatchMetricsSourceName: !Ref Section4bCloudWatchMetricsSourceName
        CloudWatchMetricsNameSpaces: "AWS/RDS"
        CreateCloudTrailLogSource: !Ref Section5cCreateCloudTrailLogSource
        CreateCloudTrailBucket: !Ref Section5aCreateCloudTrailBucket
        CloudTrailLogsBucketName: !Ref Section5bCloudTrailLogsBucketName
        CloudTrailBucketPathExpression: !Ref Section5dCloudTrailBucketPathExpression
        CloudTrailLogsSourceName: !Ref Section5eCloudTrailLogsSourceName
        TemplatesBucketName: !Ref Section6bTemplatesBucketName

  TagAWSResources:
    Type: Custom::TagAWSResources
    Condition: tag_existing_aws_resources
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      Region: !Ref "AWS::Region"
      AWSResource: rds
      Tags:
        account: !Ref Section2bAccountAlias
      AccountID: !Ref "AWS::AccountId"
      Filter: !Ref Section2cFilterExpression

  ClusterMetricRule:
    Type: Custom::SumoLogicMetricRules
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      RemoveOnDeleteStack: false
      MetricRuleName: "AwsObservabilityRDSClusterMetricsEntityRule"
      MatchExpression: "Namespace=AWS/RDS DBClusterIdentifier=*"
      ExtractVariables:
        entity: "$DBClusterIdentifier._1"
        dbidentifier: "$DBClusterIdentifier._1"
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  InstanceMetricRule:
    Type: Custom::SumoLogicMetricRules
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      RemoveOnDeleteStack: false
      MetricRuleName: "AwsObservabilityRDSInstanceMetricsEntityRule"
      MatchExpression: "Namespace=AWS/RDS DBInstanceIdentifier=*"
      ExtractVariables:
        entity: "$DBInstanceIdentifier._1"
        dbidentifier: "$DBInstanceIdentifier._1"
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  sumoApp:
    Type: Custom::App
    Condition: install_app
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      Region: !Ref "AWS::Region"
      AppName: "AWS Observability Rds App"
      Version: "V1.0.0"
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      FolderName: "Sumo Logic AWS Observability Apps "
      RetainOldAppOnUpdate: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

  SumoCloudTrailLogsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_cloudtrail_logs_source
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section5fCloudTrailLogsAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !Ref Section2bAccountAlias

  SumoMetricsUpdateSource:
    Type: Custom::SumoLogicUpdateFields
    Condition: update_metrics_source
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      Region: !Ref "AWS::Region"
      RemoveOnDeleteStack: !Ref Section1eRemoveSumoResourcesOnDeleteStack
      SourceApiUrl: !Ref Section4cCloudWatchExistingSourceAPIUrl
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment
      Fields:
        account: !Ref Section2bAccountAlias

  FieldExtractionRule:
    Type: Custom::SumoLogicFieldExtractionRule
    Condition: create_fer
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt CreateCommonResources.Outputs.LambdaHelperARN, !Ref Section6aParentStackLambdaARN]
      RemoveOnDeleteStack: false
      FieldExtractionRuleName: "AwsObservabilityRdsCloudTrailLogsFER"
      FieldExtractionRuleScope: !Join
        - ""
        - - "(_source="
          - !If [update_cloudtrail_logs_source, !Sub "\"${SumoCloudTrailLogsUpdateSource.source_name}\"", !Ref Section5eCloudTrailLogsSourceName]
          - " (\"rds.amazonaws.com\"))"
      FieldExtractionRuleParseExpression: '| json "eventSource", "awsRegion", "requestParameters", "responseElements" as eventSource, region, requestParameters, responseElements nodrop
                                           | where eventSource = "rds.amazonaws.com"
                                           | "aws/rds" as namespace
                                           | json field=requestParameters "dBInstanceIdentifier", "resourceName", "dBClusterIdentifier" as dBInstanceIdentifier1, resourceName, dBClusterIdentifier1 nodrop
                                           | json field=responseElements "dBInstanceIdentifier" as dBInstanceIdentifier3 nodrop | json field=responseElements "dBClusterIdentifier" as dBClusterIdentifier3 nodrop
                                           | parse field=resourceName "arn:aws:rds:*:db:*" as f1, dBInstanceIdentifier2 nodrop | parse field=resourceName "arn:aws:rds:*:cluster:*" as f1, dBClusterIdentifier2 nodrop
                                           | if (resourceName matches "arn:aws:rds:*:db:*", dBInstanceIdentifier2, if (!isEmpty(dBInstanceIdentifier1), dBInstanceIdentifier1, dBInstanceIdentifier3) ) as dBInstanceIdentifier
                                           | if (resourceName matches "arn:aws:rds:*:cluster:*", dBClusterIdentifier2, if (!isEmpty(dBClusterIdentifier1), dBClusterIdentifier1, dBClusterIdentifier3) ) as dBClusterIdentifier
                                           | if (isEmpty(dBInstanceIdentifier), dBClusterIdentifier, dBInstanceIdentifier) as dbidentifier
                                           | tolowercase(dbidentifier) as dbidentifier
                                           | fields region, namespace, dBInstanceIdentifier, dBClusterIdentifier, dbidentifier'
      FieldExtractionRuleParseEnabled: true
      SumoAccessID: !Ref Section1bSumoAccessID
      SumoAccessKey: !Ref Section1cSumoAccessKey
      SumoDeployment: !Ref Section1aSumoDeployment

Outputs:
  ExistingMetricSourceName:
    Description: "Existing CloudWatch Metrics Source Name"
    Condition: update_metrics_source
    Value: !GetAtt SumoMetricsUpdateSource.source_name
  ExistingLogSourceName:
    Description: "Existing CloudTrail Logs Source Name"
    Condition: update_cloudtrail_logs_source
    Value: !GetAtt SumoCloudTrailLogsUpdateSource.source_name


