AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Lambda Function for  auto enable s3 logs for S3 Buckets, VPCs, Subnets, Network Interfaces and Application load balancer."

Globals:
  Function:
    Timeout: 300
    MemorySize: 128

Mappings:
  Region2ELBAccountId:
    us-east-1:
      AccountId: "127311923021"
    us-east-2:
      AccountId: "033677994240"
    us-west-1:
      AccountId: "027434742980"
    us-west-2:
      AccountId: "797873946194"
    af-south-1:
      AccountId: "098369216593"
    ca-central-1:
      AccountId: "985666609251"
    eu-central-1:
      AccountId: "054676820928"
    eu-west-1:
      AccountId: "156460612806"
    eu-west-2:
      AccountId: "652711504416"
    eu-south-1:
      AccountId: "635631232127"
    eu-west-3:
      AccountId: "009996457667"
    eu-north-1:
      AccountId: "897822967062"
    ap-east-1:
      AccountId: "754344448648"
    ap-northeast-1:
      AccountId: "582318560864"
    ap-northeast-2:
      AccountId: "600734575887"
    ap-northeast-3:
      AccountId: "383597477331"
    ap-southeast-1:
      AccountId: "114774131450"
    ap-southeast-2:
      AccountId: "783225319266"
    ap-south-1:
      AccountId: "718504428378"
    me-south-1:
      AccountId: "076674570225"
    sa-east-1:
      AccountId: "507241528517"
    us-gov-west-1:
      AccountId: "048591011584"
    us-gov-east-1:
      AccountId: "190560391635"
    cn-north-1:
      AccountId: "638102146993"
    cn-northwest-1:
      AccountId: "037604701340"

  RegionMap:
    us-east-1:
      bucketname: appdevzipfiles-us-east-1
    us-east-2:
      bucketname: appdevzipfiles-us-east-2
    us-west-1:
      bucketname: appdevzipfiles-us-west-1
    us-west-2:
      bucketname: appdevzipfiles-us-west-2
    ap-south-1:
      bucketname: appdevzipfiles-ap-south-1
    ap-northeast-2:
      bucketname: appdevzipfiles-ap-northeast-2
    ap-southeast-1:
      bucketname: appdevzipfiles-ap-southeast-1
    ap-southeast-2:
      bucketname: appdevzipfiles-ap-southeast-2
    ap-northeast-1:
      bucketname: appdevzipfiles-ap-northeast-1
    ca-central-1:
      bucketname: appdevzipfiles-ca-central-1
    eu-central-1:
      bucketname: appdevzipfiles-eu-central-1
    eu-west-1:
      bucketname: appdevzipfiles-eu-west-1
    eu-west-2:
      bucketname: appdevzipfiles-eu-west-2
    eu-west-3:
      bucketname: appdevzipfiles-eu-west-3
    eu-north-1:
      bucketname: appdevzipfiles-eu-north-1s
    sa-east-1:
      bucketname: appdevzipfiles-sa-east-1
    ap-east-1:
      bucketname: appdevzipfiles-ap-east-1s
    af-south-1:
      bucketname: appdevzipfiles-af-south-1s
    eu-south-1:
      bucketname: appdevzipfiles-eu-south-1
    me-south-1:
      bucketname: appdevzipfiles-me-south-1s

Parameters:
  EnableLogging:
    Type: String
    Description: "ALB - To Enable S3 Logging for new Application Load Balancer."
    AllowedPattern: ".+"
    AllowedValues:
      - 'ALB'

  TaggingResourceOptions:
    Type: String
    Description: "New - Automatically enables S3 logging for newly created AWS resources to send logs to S3 Buckets. This does not affect AWS resources already collecting logs.
                  Existing - Automatically enables S3 logging for existing AWS resources to send logs to S3 Buckets.
                  Both - Automatically enables S3 logging for new and existing AWS resources.
                  None - Skips Automatic S3 Logging enable for AWS resources."
    Default: 'Both'
    AllowedValues:
      - 'New'
      - 'Existing'
      - 'Both'
      - 'None'

  BucketName:
    Type: String
    Description: "Provide an Existing bucket name which has ALB logs."
    AllowedPattern: ".+"

  BucketPrefix:
    Type: String
    Description: "Provide an bucket prefix."
    AllowedPattern: ".*"

  FilterExpression:
    Type: String
    Default: ""
    Description: "Provide regular expression for matching aws resources. For eg;- 'InstanceType': 't1.micro.*?'|'name': 'Test.*?']|'stageName': 'prod.*?'|'FunctionName': 'Test.*?'|TableName.*?|'LoadBalancerName': 'Test.*?'|'DBClusterIdentifier': 'Test.*?'|'DBInstanceIdentifier': 'Test.*?'"

  RemoveOnDeleteStack:
    AllowedValues:
      - true
      - false
    Default: true
    Description: "True - To remove S3 logging or Vpc flow logs.
                  False - To keep the S3 logging."
    Type: String

  ParentStackLambdaARN:
    Type: String
    Default: "ParentStackLambdaARN"
    Description: Parent Stack Lambda ARN. Do Not Edit the value.

Conditions:
  enable_alb_logging: !And
    - !Equals [!Ref EnableLogging, 'ALB']
    - !Condition auto_enable_new

  auto_enable_existing: !Or
    - !Equals [ !Ref TaggingResourceOptions, 'Existing' ]
    - !Equals [ !Ref TaggingResourceOptions, 'Both' ]
  auto_enable_new: !Or
    - !Equals [ !Ref TaggingResourceOptions, 'New' ]
    - !Equals [ !Ref TaggingResourceOptions, 'Both' ]

  do_not_use_parent_stack: !And
    - !Equals [ !Ref ParentStackLambdaARN, "ParentStackLambdaARN"]
    - !Condition auto_enable_existing

Resources:

  SumoLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AwsObservabilityLambdaExecutePolicies
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - elasticloadbalancing:DescribeLoadBalancerAttributes
                  - elasticloadbalancing:DescribeLoadBalancers
                  - elasticloadbalancing:ModifyLoadBalancerAttributes
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - s3:GetBucketPolicy
                  - s3:PutBucketPolicy
                Resource: '*'

  EnableNewAWSResourcesLambda:
    Type: AWS::Lambda::Function
    Condition: auto_enable_new
    Properties:
      Code:
        S3Bucket: !FindInMap [RegionMap, !Ref 'AWS::Region', bucketname]
        S3Key: "sumologic-aws-observability/apps/SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelperv2.0.2.zip"
      Handler: "awsresource.enable_s3_logs"
      Runtime: python3.7
      Role: !GetAtt SumoLambdaRole.Arn
      Description: "Lambda Function for auto enable s3 logs for AWS Resources."
      MemorySize: 128
      Timeout: 600
      Environment:
        Variables:
          BucketName: !Ref BucketName
          AccountID: !Ref "AWS::AccountId"
          Filter: !Ref FilterExpression
          BucketPrefix: !Ref BucketPrefix
          RegionAccountId: !FindInMap [Region2ELBAccountId, !Ref 'AWS::Region', AccountId]

  AutoEnableAlbLogEventsInvokePermission:
    Type: AWS::Lambda::Permission
    Condition: enable_alb_logging
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref EnableNewAWSResourcesLambda
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt AutoEnableAlbLogEventsRuleTrigger.Arn

  AutoEnableAlbLogEventsRuleTrigger:
    Type: 'AWS::Events::Rule'
    Condition: enable_alb_logging
    Properties:
      Description: Auto-Enable S3 logging for ALB resources with Lambda from events
      EventPattern:
        source:
          - aws.elasticloadbalancing
        detail-type:
          - AWS API Call via CloudTrail
        detail:
          eventSource:
            - elasticloadbalancing.amazonaws.com
          eventName:
            - CreateLoadBalancer
      Name: !Join
        - ""
        - - "sumo-logic-alb-s3-"
          - !Select
            - 0
            - !Split
              - "-"
              - !Select
                - 2
                - !Split ["/", !Ref "AWS::StackId"]
      State: ENABLED
      Targets:
        - Arn: !GetAtt EnableNewAWSResourcesLambda.Arn
          Id: Main

  EnableExisitngAWSResourcesLambda:
    Type: 'AWS::Serverless::Function'
    Condition: do_not_use_parent_stack
    Properties:
      Handler: main.handler
      Runtime: python3.7
      CodeUri:
        Bucket: !FindInMap [RegionMap, !Ref 'AWS::Region', bucketname]
        Key: "sumologic-aws-observability/apps/SumoLogicAWSObservabilityHelper/SumoLogicAWSObservabilityHelperv2.0.2.zip"
      MemorySize: 128
      Timeout: 900
      Role: !GetAtt SumoLambdaRole.Arn

  ExistingAWSResources:
    Type: Custom::EnableS3LogsResources
    Condition: auto_enable_existing
    Properties:
      ServiceToken: !If [do_not_use_parent_stack, !GetAtt EnableExisitngAWSResourcesLambda.Arn, !Ref ParentStackLambdaARN]
      AWSResource: "elbv2"
      BucketName: !Ref BucketName
      Filter: !Ref FilterExpression
      BucketPrefix: !Ref BucketPrefix
      AccountID: !Ref "AWS::AccountId"
      RegionAccountId: !FindInMap [Region2ELBAccountId, !Ref 'AWS::Region', AccountId]
      RemoveOnDeleteStack: !Ref RemoveOnDeleteStack

Outputs:

  EnableNewAWSResourcesLambda:
    Description: "EnableNewAWSResourcesLambda Function ARN"
    Value: !GetAtt EnableNewAWSResourcesLambda.Arn
    Condition: auto_enable_new
